name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Build tnode
        uses: ros-tooling/action-ros-ci@0.3.16
        with:
          package-name: tnode
          target-ros2-distro: humble
