name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install colcon and rosdep
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-rosdep
          rosdep init
          rosdep update

      - name: Build tnode
        uses: ros-tooling/action-ros-ci@0.3.16
        with:
          package-name: tnode
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos

      - name: Run colcon build
        run: colcon build

      - name: Run colcon test
        run: colcon test
